title: Immersive Performance Panel — LITE
description: Lightweight NUI performance panel for FiveM
remote_theme: just-the-docs/just-the-docs
search_enabled: true
heading_anchors: true
color_scheme: dark
footer_content: "© 2026 Immersive RP. Released under the MIT License."
